-- schema.sql — PostGIS schema for MAPC Zoning Atlas ETL
--
-- Run this once against your AWS RDS PostGIS instance before the first ETL run:
--   psql -h <RDS_HOST> -U <USER> -d <DBNAME> -f sql/schema.sql
--
-- CRS: All geometry stored in EPSG:26986 (NAD83 / Massachusetts Mainland, metres).
--      Use ST_Transform(geometry, 4326) in queries that serve web maps.

-- ── Extensions ────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Schema ────────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS mapc;

-- ── Main zoning table ────────────────────────────────────────────────────────
-- Column names mirror MAPC Zoning Atlas field names (lowercased).
-- The ETL pipeline populates this table via GeoDataFrame.to_postgis().
-- Nullable columns reflect that not all municipalities populate all fields.
CREATE TABLE IF NOT EXISTS mapc.zoning_atlas (
    -- Surrogate key (generated by PostGIS on insert)
    id              SERIAL PRIMARY KEY,

    -- MAPC identifiers
    muni_id         TEXT,             -- Municipality numeric ID
    muni_name       TEXT,             -- Municipality name (e.g. "Cambridge")
    zo_id           TEXT,             -- Unique zoning district ID
    zo_abbr         TEXT,             -- Zoning abbreviation (e.g. "R1", "B2")
    zo_name         TEXT,             -- Full district name
    zo_usety        TEXT,             -- Use type category (residential/commercial/etc.)

    -- Housing-related fields (may be null for non-residential zones)
    multifam        TEXT,             -- Multifamily housing allowed?
    aff_req         TEXT,             -- Affordable housing requirement
    by_right        TEXT,             -- Multifamily allowed by-right (vs. special permit)

    -- Derived fields added by transform step
    area_m2         NUMERIC(18, 2),   -- Feature area in square metres (EPSG:26986)
    area_acres      NUMERIC(12, 4),   -- Feature area in acres
    centroid_x      NUMERIC(12, 2),   -- Centroid easting (EPSG:26986)
    centroid_y      NUMERIC(12, 2),   -- Centroid northing (EPSG:26986)

    -- ETL provenance
    etl_run_id      TEXT NOT NULL,    -- UUID of the pipeline run that loaded this row
    etl_loaded_at   TIMESTAMPTZ,      -- UTC timestamp of the load

    -- Geometry: NAD83 / Massachusetts Mainland (EPSG:26986)
    -- Use ST_Transform(geometry, 4326) for web map queries
    geometry        GEOMETRY(MultiPolygon, 26986)
);

COMMENT ON TABLE  mapc.zoning_atlas                IS 'MAPC Greater Boston Zoning Atlas — zoning district polygons for 101 municipalities. Source: https://www.mapc.org/planning101/zoning-atlas/';
COMMENT ON COLUMN mapc.zoning_atlas.geometry       IS 'Zoning district boundary. CRS: EPSG:26986 (NAD83 / Massachusetts Mainland). Use ST_Transform(geometry, 4326) for web map output.';
COMMENT ON COLUMN mapc.zoning_atlas.area_m2        IS 'District area in square metres, calculated in EPSG:26986 (accurate for Massachusetts).';
COMMENT ON COLUMN mapc.zoning_atlas.etl_run_id     IS 'UUID linking this row to the etl_runs audit table.';

-- ── Spatial index ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_zoning_atlas_geom
    ON mapc.zoning_atlas USING GIST (geometry);

-- ── Attribute indexes (for common filter queries) ─────────────────────────────
CREATE INDEX IF NOT EXISTS idx_zoning_atlas_muni_id  ON mapc.zoning_atlas (muni_id);
CREATE INDEX IF NOT EXISTS idx_zoning_atlas_zo_usety ON mapc.zoning_atlas (zo_usety);
CREATE INDEX IF NOT EXISTS idx_zoning_atlas_etl_run  ON mapc.zoning_atlas (etl_run_id);

-- ── ETL audit table ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mapc.etl_runs (
    run_id       TEXT PRIMARY KEY,
    table_name   TEXT NOT NULL,
    row_count    INTEGER,
    started_at   TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);

COMMENT ON TABLE mapc.etl_runs IS 'Audit log of each ETL pipeline run — one row per execution.';

-- ── QA/QC log table ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mapc.qaqc_log (
    id          SERIAL PRIMARY KEY,
    run_id      TEXT NOT NULL REFERENCES mapc.etl_runs(run_id) ON DELETE CASCADE,
    check_name  TEXT NOT NULL,
    passed      BOOLEAN NOT NULL,
    value       TEXT,             -- Actual observed value (cast to text for flexibility)
    threshold   TEXT,             -- Expected threshold / limit
    critical    BOOLEAN NOT NULL, -- True if failure should halt the pipeline
    note        TEXT,
    checked_at  TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE  mapc.qaqc_log            IS 'QA/QC check results per ETL run. Join to etl_runs on run_id.';
COMMENT ON COLUMN mapc.qaqc_log.critical   IS 'If true, a failed check means the pipeline should not proceed.';
COMMENT ON COLUMN mapc.qaqc_log.value      IS 'The observed metric value (e.g. null rate, feature count).';
COMMENT ON COLUMN mapc.qaqc_log.threshold  IS 'The acceptable limit this check is evaluated against.';

CREATE INDEX IF NOT EXISTS idx_qaqc_log_run_id ON mapc.qaqc_log (run_id);
